config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'plaincv', to: 'pages#plaincv'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'personal_info', to: 'personal_info#display'
  get 'edit_personal_info', to: 'personal_info#edit'
  patch 'edit_personal_info', to: 'personal_info#update'

  resources :users, only: [:edit, :update]
  resources :tools
  resources :career_infos
  resources :courses
  resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :academics, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'visitors', to: 'pages#visitors'

  get 'visitors_json', to: 'pages#visitors_json'
  get 'visitors_json_today', to: 'pages#visitors_json_today'
  get 'visitors_json_week', to: 'pages#visitors_json_week'
  get 'visitors_json_yesterday', to: 'pages#visitors_json_yesterday'

  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get 'flush_visitors', to: 'pages#flush_visitors'

end

app/models/tool.rb
class Tool < ApplicationRecord
  validates :name, presence: true
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :require_user, except: %i[index]
  before_action :fetch_personal_info
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.all
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
    redirect_to tools_path
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tool_params
      params.require(:tool).permit(:name)
    end

    def fetch_personal_info
      @personal_info = PersonalInfo.first
    end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<div class="main_board center-align row">
    <div class="title board_item text  block ">
      
      <div class="row">
        <div class="input-field col s12">
          <h4 style="color: #8f8f8f !important; font-weight: normal;">Conhecimentos</h4>
        </div>
      </div>

      
      <%= form_with model: @tool, local: true do |f| %>

        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :name,  class:"validate input_field", placeholder:"Excel" %>
            <%= f.label :name, "Conhecimento:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.submit "Save", class:"waves-effect waves-light btn-small amber darken-2 white-text"%>
          </div>
        </div>

      <% end %>


    </div>
</div>

app/views/tools/edit.html.erb
<%= render 'form', tool: @tool %>

app/views/tools/index.html.erb
<div class="main_board center-align row">
  <div class="title board_item text  block ">
    
      <a href="<%= root_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">Return</a>
      <% if logged_in?%>
        <a href="<%= new_tool_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">New</a>
      <% end %>
    
    <div class="row">
      <div class="input-field col s12">
        <h4 class="h4" style="margin: 0 !important;">Conhecimentos</h4>
      </div>
    </div>

    <div class="info_board center-align row"></div>

    <% @colors= ['indigo', 'grey']%>
    <% @index = 0 %>

    
        <% @tools.each do |tool| %>

          <div class="title board_item text text_greeting block <%= (@index.even?)? @colors[0] : @colors[1]%> darken-4" style="padding: 0.5em !important">
  
            <ul style="padding: 0 !important; margin: 0 !important;">
              <li>
                  <%= tool.name %>
              </li>
              <% if logged_in?%>
                <li>
                  <%= link_to  "Edit", edit_tool_path(tool), style: 'text-decoration: none !important; color: black !important; font-weight: normal; margin: 0; padding: 0'  %>
                  <%= link_to  "Delete", tool_path(tool), method: :delete, style: 'text-decoration: none !important; color: red !important; font-weight: normal; margin: 0; padding: 0' %>
                </li>
              <% end %>
            </ul>
          </div>

        <% @index += 1 %>
        <% end %>


    </div>
    

  </div>
</div>

app/views/tools/new.html.erb
<%= render 'form', tool: @tool %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tool.name %>
</p>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>