config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'plaincv', to: 'pages#plaincv'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'personal_info', to: 'personal_info#display'
  get 'edit_personal_info', to: 'personal_info#edit'
  patch 'edit_personal_info', to: 'personal_info#update'

  resources :users, only: [:edit, :update]
  resources :tools
  resources :career_infos
  resources :courses
  resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :academics, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'visitors', to: 'pages#visitors'

  get 'visitors_json', to: 'pages#visitors_json'
  get 'visitors_json_today', to: 'pages#visitors_json_today'
  get 'visitors_json_week', to: 'pages#visitors_json_week'
  get 'visitors_json_yesterday', to: 'pages#visitors_json_yesterday'

  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get 'flush_visitors', to: 'pages#flush_visitors'

end

app/models/academic.rb
class Academic < ApplicationRecord
  enum done: { Nao_Concluido: 0, Concluido: 1 }
  validates :institution, presence: true
  validates :course, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :done, presence: true
end

app/controllers/academics_controller.rb
class AcademicsController < ApplicationController
  before_action :require_user, except: %i[index]
  before_action :fetch_personal_info

  def index
    @academics = Academic.all
    @languages = Language.all
  end

  def new
    @academic = Academic.new()
  end

  def create
    @academic = Academic.new(academic_params)
    return redirect_to academics_path if @academic.save
    flash.now[:alert] = "Campo não pode ficar vazio"
    render :new
  end

  def edit
    @academic = Academic.find(params[:id])
  end

  def update
    @academic = Academic.find(params[:id])
    return redirect_to academics_path if @academic.update(academic_params)
    flash.now[:alert] = "Campo não pode ficar vazio"
    render :new
  end

  def destroy
    @academic = Academic.find(params[:id])
    @academic.delete
    redirect_to academics_path
  end

  private

  def academic_params
    params.require(:academic).permit(:institution, :course, :start_date,
                                     :end_date, :done)
  end

  def fetch_personal_info
    @personal_info = PersonalInfo.first
  end
end

app/views/academics/_form.html.erb
<div class="main_board center-align row">
    <div class="title board_item text  block ">
      
      <div class="row">
        <div class="input-field col s12">
          <h4 style="color: #8f8f8f !important; font-weight: normal;">Academics</h4>
        </div>
      </div>


      <% @done_opt = ['Nao_Concluido','Concluido']%>
      
      <%= form_with model: @academic, local: true do |f| %>

        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :institution,  class:"validate input_field", placeholder:"School" %>
            <%= f.label :institution, "Instituição:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :course,  class:"validate input_field", placeholder:"Direito" %>
            <%= f.label :course, "Curso:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.date_field :start_date,  class:"datepicker validate input_field" %>
            <%= f.label :start_date, "Início:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.date_field :end_date,  class:"datepicker validate input_field" %>
            <%= f.label :end_date, "Fim:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.select(:done, @done_opt, { }, { :style => 'display: block !important;' }) %>

            
          </div>
        </div>


        <div class="row">
          <div class="input-field col s12">
            <%= f.submit "Save", class:"waves-effect waves-light btn-small amber darken-2 white-text"%>
          </div>
        </div>

      <% end %>


    </div>
</div>

app/views/academics/edit.html.erb
<%= render  "form" %>

app/views/academics/index.html.erb
<div class="main_board center-align row">
    <div class="title board_item text  block ">
      
        <a href="<%= root_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">Return</a>
        <% if logged_in?%>
          <a href="<%= new_academic_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">New</a>
        <% end %>
      
      <div class="row">
        <div class="input-field col s12">
          <h4 class="h4" style="margin: 0 !important;">Formação</h4>
        </div>
      </div>

      <div class="info_board center-align row"></div>


      <% @academics.each do |academic| %>

        <div class="title board_item text text_greeting block lime darken-4" style="padding: 0.5em !important;">
        
          <ul style="padding: 0 !important; margin: 0 !important;">
            <li>
              <%= academic.institution %>
            </li>
            <li>
              <%= academic.course %>
            </li>
            <li>
              Início: <%= academic.start_date.month %>/<%= academic.start_date.year %>
              <% if academic.done == 'Concluido'%>
               - Fim: <%= academic.end_date.month %>/<%= academic.end_date.year %>
              <% else %>

              <% end %>
            </li>
            <% if logged_in?%>
              <li>
                <%= link_to  "Edit", edit_academic_path(academic), style: 'text-decoration: none !important; color: black !important; font-weight: normal; margin: 0; padding: 0'  %>
                <%= link_to  "Delete", academic_path(academic), method: :delete, style: 'text-decoration: none !important; color: red !important; font-weight: normal; margin: 0; padding: 0' %>
              </li>
            <% end %>
          </ul>
        </div>
        </p>
      <% end %>

      <hr>

      <div class="row">
        <div class="input-field col s12">
          <h4 class="h4" style="margin: 0 !important;">Idiomas</h4>
        </div>
      </div>

      <% @languages.each do |language| %>

        <div class="title board_item text text_greeting block indigo darken-4" style="padding: 0.5em !important;">
        
          <ul style="padding: 0 !important; margin: 0 !important;">
            <li>
              <%= language.institution %>
            </li>
            <li>
              <%= language.language %>
            </li>
            <li>
              Início: <%= language.start_date.month %>/<%= language.start_date.year %>
              
               - Fim: <%= language.end_date.month %>/<%= language.end_date.year %>
            </li>
            <li>
              <%= language.level %>
            </li>
            <% if logged_in?%>
              <li>
                <%= link_to  "Edit", edit_language_path(language), style: 'text-decoration: none !important; color: black !important; font-weight: normal; margin: 0; padding: 0'  %>
                <%= link_to  "Delete", language_path(language), method: :delete, style: 'text-decoration: none !important; color: red !important; font-weight: normal; margin: 0; padding: 0' %>
              </li>
            <% end %>
          </ul>
        </div>
        </p>
      <% end %>


      </div>
      

    </div>
</div>

app/views/academics/new.html.erb
<%= render  "form" %>