config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'plaincv', to: 'pages#plaincv'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'personal_info', to: 'personal_info#display'
  get 'edit_personal_info', to: 'personal_info#edit'
  patch 'edit_personal_info', to: 'personal_info#update'

  resources :users, only: [:edit, :update]
  resources :tools
  resources :career_infos
  resources :courses
  resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :academics, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'visitors', to: 'pages#visitors'

  get 'visitors_json', to: 'pages#visitors_json'
  get 'visitors_json_today', to: 'pages#visitors_json_today'
  get 'visitors_json_week', to: 'pages#visitors_json_week'
  get 'visitors_json_yesterday', to: 'pages#visitors_json_yesterday'

  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get 'flush_visitors', to: 'pages#flush_visitors'

end

app/models/career_info.rb
class CareerInfo < ApplicationRecord
  validates :company, presence: true
  validates :work_function, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :description, presence: true
end

app/controllers/career_infos_controller.rb
class CareerInfosController < ApplicationController
  before_action :require_user, except: %i[index show]
  before_action :fetch_personal_info
  before_action :set_career_info, only: [:show, :edit, :update, :destroy]

  # GET /career_infos
  # GET /career_infos.json
  def index
    @career_infos = CareerInfo.all.order(end_date: :desc)
  end

  # GET /career_infos/1
  # GET /career_infos/1.json
  def show
  end

  # GET /career_infos/new
  def new
    @career_info = CareerInfo.new
  end

  # GET /career_infos/1/edit
  def edit
  end

  # POST /career_infos
  # POST /career_infos.json
  def create
    @career_info = CareerInfo.new(career_info_params)

    respond_to do |format|
      if @career_info.save
        format.html { redirect_to @career_info, notice: 'Career info was successfully created.' }
        format.json { render :show, status: :created, location: @career_info }
      else
        format.html { render :new }
        format.json { render json: @career_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /career_infos/1
  # PATCH/PUT /career_infos/1.json
  def update
    respond_to do |format|
      if @career_info.update(career_info_params)
        format.html { redirect_to @career_info, notice: 'Career info was successfully updated.' }
        format.json { render :show, status: :ok, location: @career_info }
      else
        format.html { render :edit }
        format.json { render json: @career_info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /career_infos/1
  # DELETE /career_infos/1.json
  def destroy
    @career_info.destroy
    respond_to do |format|
      format.html { redirect_to career_infos_url, notice: 'Career info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_career_info
      @career_info = CareerInfo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def career_info_params
      params.require(:career_info).permit(:company, :work_function, :start_date, :end_date, :description)
    end

    def fetch_personal_info
      @personal_info = PersonalInfo.first
    end
end

app/helpers/career_infos_helper.rb
module CareerInfosHelper
end

app/views/career_infos/_form.html.erb
<div class="main_board center-align row">
    <div class="title board_item text  block ">
      
      <div class="row">
        <div class="input-field col s12">
          <h4 style="color: #8f8f8f !important; font-weight: normal;">Experiência profissional</h4>
        </div>
      </div>

      
      <%= form_with model: @career_info, local: true do |f| %>

        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :company,  class:"validate input_field", placeholder:"Empresa" %>
            <%= f.label :company, "Empresa:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.text_field :work_function,  class:"validate input_field", placeholder:"Contador" %>
            <%= f.label :work_function, "Cargo:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.date_field :start_date,  class:"datepicker validate input_field" %>
            <%= f.label :start_date, "Início:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.date_field :end_date,  class:"datepicker validate input_field" %>
            <%= f.label :end_date, "Fim:"%>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <%= f.text_area :description,  class:"validate input_field", placeholder:"" %>
            <%= f.label :description, "Descrição:"%>
          </div>
        </div>


        <div class="row">
          <div class="input-field col s12">
            <%= f.submit "Save", class:"waves-effect waves-light btn-small amber darken-2 white-text"%>
          </div>
        </div>

      <% end %>


    </div>
</div>

app/views/career_infos/edit.html.erb
<%= render 'form', career_info: @career_info %>

app/views/career_infos/index.html.erb
<div class="main_board center-align row">
  <div class="title board_item text  block ">
    
      <a href="<%= root_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">Return</a>
      <% if logged_in?%>
        <a href="<%= new_career_info_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">New</a>
      <% end %>
    
    <div class="row">
      <div class="input-field col s12">
        <h4 class="h4" style="margin: 0 !important;">Experiência profissional</h4>
      </div>
    </div>

    <div class="info_board center-align row"></div>

    <% @colors= ['indigo', 'grey']%>
    <% @index = 0 %>

    
        <% @career_infos.each do |career_info| %>

          <div class="title board_item text text_greeting block <%= (@index.even?)? @colors[0] : @colors[1]%> darken-4" style="padding: 0.5em !important">
  
            <ul style="padding: 0 !important; margin: 0 !important;">
              <li>
                  <%= career_info.company %>
              </li>
              <hr/>
              <li>
                <%= career_info.work_function %>
              </li>
              <li>
                Início: <%= career_info.start_date.month %>/<%= career_info.start_date.year %>
                <% unless career_info.end_date.nil?%>
                - Fim: <%= career_info.end_date.month %>/<%= career_info.end_date.year %>
                <% else %>

                <% end %>
            </li>
              <li>
                <%= link_to  "Detalhes", career_info_path(career_info), style: 'text-decoration: none !important; color: dark-grey !important; font-weight: normal; margin: 0; padding: 0'  %>
              </li>
              <% if logged_in?%>
                <li>
                  <%= link_to  "Edit", edit_career_info_path(career_info), style: 'text-decoration: none !important; color: black !important; font-weight: normal; margin: 0; padding: 0'  %>
                  <%= link_to  "Delete", career_info_path(career_info), method: :delete, style: 'text-decoration: none !important; color: red !important; font-weight: normal; margin: 0; padding: 0' %>
                </li>
              <% end %>
            </ul>
          </div>
          </p>


        <% end %>


    </div>
    

  </div>
</div>

app/views/career_infos/new.html.erb
<%= render 'form', career_info: @career_info %>

app/views/career_infos/show.html.erb
<div class="main_board center-align row">
    <div class="title board_item text  block ">
      
        <a href="<%= career_infos_path %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">Return</a>
        <% if logged_in?%>
          <a href="<%= edit_career_info_path(@career_info) %>" style="text-decoration: none !important; color: #8f8f8f6c !important; font-weight: normal; margin: 0; padding: 0">Edit</a>
        <% end %>
      
      <div class="row">
        <div class="input-field col s12">
          <h4 class="h4" style="margin: 0 !important;">Experiência profissional</h4>
        </div>
      </div>

      <div class="info_board center-align row"></div>
        <div class="title board_item text text_greeting block blue darken-4">
            <p><%= @career_info.company %></p>
            
            <p><%= @career_info.work_function %></p>
            <p>
              Início: <%= @career_info.start_date.month %>/<%= @career_info.start_date.year %>
            </p>
              <% unless @career_info.end_date.nil?%>
                <p>
                  Fim: <%= @career_info.end_date.month %>/<%= @career_info.end_date.year %>
                </p>
              <% else %>

              <% end %>
            </p>

        </div>
        <div class="title board_item text text_greeting block lime darken-3">
          <p><%= @career_info.description %></p>
            
        </div>
      </div>
      

    </div>
</div>