config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'plaincv', to: 'pages#plaincv'

  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  get 'dashboard', to: 'pages#dashboard'

  get 'personal_info', to: 'personal_info#display'
  get 'edit_personal_info', to: 'personal_info#edit'
  patch 'edit_personal_info', to: 'personal_info#update'

  resources :users, only: [:edit, :update]
  resources :tools
  resources :career_infos
  resources :courses
  resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
  resources :academics, only: [:index, :new, :create, :edit, :update, :destroy]

  get 'visitors', to: 'pages#visitors'

  get 'visitors_json', to: 'pages#visitors_json'
  get 'visitors_json_today', to: 'pages#visitors_json_today'
  get 'visitors_json_week', to: 'pages#visitors_json_week'
  get 'visitors_json_yesterday', to: 'pages#visitors_json_yesterday'

  resources :projects, only: [:index, :new, :create, :show, :edit, :update, :destroy]

  get 'flush_visitors', to: 'pages#flush_visitors'

end

app/views/shared/_footer.html.erb
<div id='my_footer' class="amber darken-2">
  <div class="info_board center-align row"></div>
    <div class="board_item text text_greeting amber darken-2">
        <%= @personal_info.footer_text%>
        <br>
        This project's code can be found <a href="https://github.com/xitarps/curriculo" style="color: blue !important;">Here</a>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav>
  <div class="nav-wrapper amber darken-2">
    <a href="<%= root_path %>" class="brand-logo">
        <i class="material-icons">home</i>Home
                  </a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <% if !logged_in? %>
        <li>
          <%= link_to  "Sign in", signin_path %>
        </li>
      <% else %>
        <li>
          <%= link_to  "Dashboard", dashboard_path %>
        </li>
        <li>
          <%= link_to  "Sign out", signout_path, method: :delete %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">

<% if !logged_in? %>
  <li>
    <%= link_to signin_path do %>
    &#128274; Sign in
    <% end %>
  </li>
<% else %>
  <li>
    <%= link_to  "Dashboard", dashboard_path %>
  </li>
  <li>
    <%= link_to  "Sign out", signout_path, method: :delete %>
  </li>
<% end %>
  
  

  

</ul>  

app/views/shared/_notice_and_alert.html.erb
<% if notice %>
  <%= javascript_tag "M.toast({html: '#{notice}'}, 9000)" unless notice.nil? %>
<% end %>
<% if alert %>
  <%= javascript_tag "M.toast({html: '#{alert}'}, 9000)" unless alert.nil? %>
<% end %>